#!/bin/sh
clear

function writeJSON {
  arr=();

while read x y;
do
    arr=("${arr[@]}" $x $y)
done

vars=(${arr[@]})
len=${#arr[@]}

printf "{"
for (( i=0; i<len; i+=2 ))
do
    printf "\"${vars[i]}\": ${vars[i+1]}"
    if [ $i -lt $((len-2)) ] ; then
        printf ", "
    fi
done
printf "}"
echo
}

function readJson {
  UNAMESTR=`uname`
  if [[ "$UNAMESTR" == 'Linux' ]]; then
    SED_EXTENDED='-r'
  elif [[ "$UNAMESTR" == 'Darwin' ]]; then
    SED_EXTENDED='-E'
  fi;

  VALUE=`grep -m 1 "\"${2}\"" ${1} | sed ${SED_EXTENDED} 's/^ *//;s/.*: *"//;s/",?//'`

  if [ ! "$VALUE" ]; then
    echo "Error: Cannot find \"${2}\" in ${1}" >&2;
    exit 1;
  else
    echo $VALUE ;
  fi;
}

function ask_user() {
toilet -f future "TwitterCLI installer" --filter gay
echo "
#~~~~~~~~~~~~~~~~~~~~~~~~#
| 1.) Install for OSX    |
| 2.) Check 4 updates    |
| 3.) Setup Access Keys  |
| 0.) Exit	         |
#~~~~~~~~~~~~~~~~~~~~~~~~#\n"
tput bold
tput setaf 6
read -e -p "==> " choice
tput sgr0
if [ "$choice" == "1" ]; then

    pip install -r requirements.txt
elif [ "$choice" == "2" ]; then
    echo "checking for updates..."
    NewestVersion=$(curl -s 'https://isn0we.github.io/TwitterCLI/OSX/DontTouch.json' | jq -r '.version')
    echo "The newest version aviable is: $NewestVersion"
    InstalledV=$(readJson DontTouch.json version)
    echo "Your installed version is: $InstalledV"
    if [ "$InstalledV" == "$NewestVersion" ]; then
        echo "You Are up to date!"
    else
      	echo "A new TwitterCLI is aviable! You will be prompted to a update screen in a few seconds."
      	sleep 5
      	clear
      	toilet -f future "TwitterCLI Update" --filter gay
      	tput bold
      	tput setaf 2
      	echo "Downloading newer version of TwitterCLI..."
        wget https://isn0we.github.io/TwitterCLI/OSX/PackageZIP/OSX.zip
	echo "Downloaded. installing..."
	unzip -qq -o OSX.zip
	rm -rf OSX.zip
	echo "Installed successfully!"
    fi
elif [ "$choice" == "3" ]; then
    clear
    toilet -f future "Setup Access Keys" --filter gay
    echo "1. Go to https://apps.twitter.com and create a new Application."
    echo "2. Open the Access token site, so you can see all your access tokens."
    echo "3. When you're ready to start, hit enter."
    read
    read -p "Access token ==> " Access_token
    read -p "Access Secret ==> " access_secret
    read -p "Consumer Key ==> " consumer_key
    read -p "Consumer Secret ==> " consumer_secret
    echo "Writing to config json..."
    cat >./Keys.json <<EOF
    {
      "access_key": "$Access_token",
      "access_secret": "$access_secret",
      "consumer_key": "$consumer_key",
      "consumer_secret": "$consumer_secret"
    }
EOF
    echo "Wrote to Key config file."
    echo "NEVER SHARE THIS FILE WITH ANYBODY. THIS IS LIKE GIVING YOUR PASSWORD OUT!"

elif [ "$choice" == "0" ]; then

    clear
    exit

else

    echo "Please select 1, 2, or 3." && sleep 3
    clear && ask_user

fi
}

ask_user
